### ISSUE TITLE
Does TPLE support save b-tree or r-tree index file to disk?

### ISSUE THREAD

**Issue by ChenZhongPu** [thomasmoelhave/tpie#175]
I am want to read input file from `HDFS`, and build `r-tree index` of it, and want to save the index file to disk. 

I am told that the **TPLE** support building and saving r-tree index, and I cannot find it in this project. 

Does it support that on earth?

**Comment by thomasmoelhave** [comment]
Arge  et al wrote a [paper](http://dl.acm.org/citation.cfm?id=702170) about R-Trees with experiments written using TPIE. There are still some Rtree code left over in [the apps directory](https://github.com/thomasmoelhave/tpie/tree/master/apps/rtree) of the TPIE repository, but due to a lack of interest it's not been maintained for years (and not included in the default build). I doubt the code still works,  

However, TPIE recently gained support for [augmented B-trees](http://madalgo.au.dk/tpie/doc/master/btree.html) which you can probably use to generate an R tree of your data.
